### ISSUE TITLE
Need A Scoring System

### ISSUE THREAD

**Issue by scottpreston** [scottpreston/mjolnir-simulator#22]
So with each of the glass panes we need a score tabulated at the top of the screen.

**Comment by calebeno** [comment]
There is a script which contains a global game object attached to the window. ([gameObject.js](https://github.com/scottpreston/mjolnir-simulator/blob/master/client/js/src/gameObject.js)) Currently it only contains a dummy value.
**Idea:**  Create a new script which handles score change modification on the gameObject.  Possibly bind values from the global game object to a score display element.  (Honestly not sure how to do binding outside of a framework.  Could be a fun challenge for someone.)

**Comment by iamtekeste** [comment]
I have a question about this scoring system. 
1. Will there be multiple types of targets(eg Ultron, Loki, Hydra, Thanos ) displayed at the same time or is just going to be one type of target at a time/level?

**Comment by scottpreston** [comment]
initially I was thinking yes. what about coding it such that you add the targets in an array, so if there's just 1 item is one-target at a time/level, but if there's more then it displays more?

**Comment by iamtekeste** [comment]
That makes sense.  So it would start with a single target and on every level, you would have multiple targets of a different variety.
Would all the targets have the same score/point?

**Comment by scottpreston** [comment]
for now lets just start with fixed positions for each target with fixed score/points, logistically someone can't throw a hammer more than once for the game set-up.
